language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      python: 3.6.2
      sudo: false
      env: CC_COMPILER=gcc CXX_COMPILER=g++

script:
  - apt-get -y install git make gcc g++ autoconf zlib1g-dev libcurl4-openssl-dev libbz2-dev libhdf5-dev
  - cmake --version
  - $CC_COMPILER -v
  - $CXX_COMPILER -v
  - python3 --version
  - python --version
  - make install

env:
  global:
  - LANG="en_US.UTF-8"